Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Ideenstadtwerke.Neos.Content.Accordion': ['*', 'NodeTypes/*']
    fusion:
      autoInclude:
        'Ideenstadtwerke.Neos.Content.Accordion': true
